on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: commit-message-validation
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/commit-message-validation@v1
        with:
          regex: 'Mona the Octocat'
