on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: commit-message-validation
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: uptownaravi/verify-commit-message-action/.github/actions/commit-message-validation@main
        with:
          regex: 'JIRA-[0-9]{3,}'
